"""Shared declarations for the keyword-search columns (feature 011, ADR-078/081).

Every searchable table carries a `search_text` column generated by PostgreSQL from that
table's searchable fields, indexed with a trigram GIN index. Chinese text search uses
pg_trgm rather than tsvector because PostgreSQL's full-text search does not segment
Chinese — "花蓮縣光復鄉" becomes a single token and searching "光復" finds nothing.

**The set of columns feeding each `search_text` is the implementation of ADR-079's
positive list.** Before changing any generation expression, check
`Spec/011-resource-search/spec.md` §3 and update `EXPECTED_SOURCE_COLUMNS` in
`tests/test_search_schema.py` — PII (`contact_*`) and free-text note fields
(`comment` / `progress_note` / `pole_note`) must never enter the index.
"""

from sqlalchemy import Index

# 長文字欄位在 generated column 內截斷的字元數。GIN 索引條目數約等於
# 資料列數 × 可搜文字字元數,而 description 這類欄位是無長度上限的 text——
# 單列貼進 5 萬字就會產生 5 萬個條目。截斷把成本鎖成定值 (ADR-081)。
SEARCH_TEXT_TRUNCATE = 500


def truncated(column: str) -> str:
    """SQL fragment for a long text column: coalesce + truncate to SEARCH_TEXT_TRUNCATE."""
    return f"left(coalesce({column}, ''), {SEARCH_TEXT_TRUNCATE})"


def plain(column: str) -> str:
    """SQL fragment for a short text column: coalesce only, no truncation."""
    return f"coalesce({column}, '')"


def search_text_expression(*fragments: str) -> str:
    """Join field fragments into one space-separated generation expression.

    Concatenating into a single column (rather than indexing each field separately) is
    what lets a query span fields — "光復鄉中正巷" matches even though no single column
    contains the whole string (ADR-081).
    """
    return " || ' ' || ".join(fragments)


def search_text_index(table: str) -> Index:
    """Build the trigram GIN index for `table`.`search_text`.

    Naming is uniform (`ix_<table>_search_text_trgm`) so tests can assert every
    searchable table has one without a hand-maintained list of index names.
    """
    return Index(
        f"ix_{table}_search_text_trgm",
        "search_text",
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
