"""Shared declarations for the keyword-search columns (feature 011, ADR-078/081).

Every searchable table carries a `search_text` column generated by PostgreSQL from that
table's searchable fields, indexed with a trigram GIN index. Chinese text search uses
pg_trgm rather than tsvector because PostgreSQL's full-text search does not segment
Chinese — "花蓮縣光復鄉" becomes a single token and searching "光復" finds nothing.

**The set of columns feeding each `search_text` is the implementation of ADR-079's
positive list.** Before changing any generation expression, check
`Spec/011-resource-search/spec.md` §3 and update `EXPECTED_SOURCE_COLUMNS` in
`tests/test_search_schema.py` — PII (`contact_*`) and free-text note fields
(`comment` / `progress_note` / `pole_note`) must never enter the index.

**Every `search_text` column must be declared `deferred=True`** (ADR-161). Nothing in the
API exposes it — it exists only to be matched against in a WHERE clause — so left in the
default column list it is transferred and hydrated by every `select(Model)`, including
the plain list paths that never search. Deferral does not affect the search itself: the
predicates and the `similarity()` ordering reference the column as an expression, not as
a loaded attribute. `test_search_text_is_deferred_on_every_searchable_model` asserts it
for all six tables.
"""

from sqlalchemy import Index

# 長文字欄位在 generated column 內截斷的字元數。GIN 索引條目數約等於
# 資料列數 × 可搜文字字元數,而 description 這類欄位是無長度上限的 text——
# 單列貼進 5 萬字就會產生 5 萬個條目。截斷把成本鎖成定值 (ADR-081)。
SEARCH_TEXT_TRUNCATE = 500


def truncated(column: str) -> str:
    """SQL fragment for a long text column: coalesce + truncate to SEARCH_TEXT_TRUNCATE."""
    return f"left(coalesce({column}, ''), {SEARCH_TEXT_TRUNCATE})"


def plain(column: str) -> str:
    """SQL fragment for a short text column: coalesce only, no truncation."""
    return f"coalesce({column}, '')"


def search_text_expression(*fragments: str, separator: str = " ") -> str:
    """Join field fragments into one generation expression.

    Concatenating into a single column (rather than indexing each field separately) is
    what lets a query span fields at all — no single column holds the whole string.

    `separator` decides whether a query may span two fields *contiguously*. The search
    predicate is one uninterrupted ``ILIKE '%term%'`` (app/core/search.py), so anything
    put between two fragments must also appear, in that exact position, in what the user
    typed:

    - **`" "` (default)** — for fields a user would never run together, like a station's
      name and its description. A cross-field query still needs a space where the fields
      meet, which is the natural way to type "光復國小 收容所".
    - **`""`** — for fields that form one continuous string in the source domain. A
      Chinese address is written 花蓮縣光復鄉中正路, never with spaces, so
      secondary_locations concatenates with no separator (ADR-155). The cost is that
      adjacent fields can form a spurious substring across their boundary; for address
      parts that is a far smaller problem than not matching at all.
    """
    return f" || '{separator}' || ".join(fragments) if separator else " || ".join(fragments)


def search_text_index(table: str) -> Index:
    """Build the trigram GIN index for `table`.`search_text`.

    Naming is uniform (`ix_<table>_search_text_trgm`) so tests can assert every
    searchable table has one without a hand-maintained list of index names.
    """
    return Index(
        f"ix_{table}_search_text_trgm",
        "search_text",
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
