services:
  # Local db for local testing.
  db:
    image: postgis/postgis:16-3.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.db:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      - SECRET_KEY=your-secret-key-for-local-dev
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
