#!/usr/bin/env bash
# One-command staging deploy. Runbook & design rationale: Backend/DEPLOY.md.
# Usage:
#   ./scripts/deploy.sh              deploy origin/main
#   ./scripts/deploy.sh <git-ref>    deploy a tag/SHA (also the manual-rollback path)
#   SEED_MOCK=true ./scripts/deploy.sh   additionally (re)apply the mock-scenario seed
#
# -E (errtrace) is REQUIRED: without it the ERR trap does not fire for failures inside
# functions (gen_env, compose wrapper) and the rollback would be silently skipped.
set -Eeuo pipefail

export COMPOSE_FILE=docker-compose.staging.yml
# Must match the project name of the ALREADY-RUNNING stack on the VM (dir name "Backend" → "backend"),
# so existing containers/volumes (backend_pgdata, backend_redisdata) are reused, not shadowed.
export COMPOSE_PROJECT_NAME=backend

IMAGE=disaster-backend
LOCK_FILE=/var/lock/disaster-deploy.lock
GCS_BUCKET="gs://wanguard-250923-db-backups"    # created by the one-time bootstrap (30-day lifecycle)
READYZ_URL=http://localhost:8000/readyz
BACKEND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Globals shared with the failure trap
STAGE=pre            # pre -> worktree -> service
OLD_SHA=""
LAST_BACKUP="(none)"

compose() { docker compose "$@"; }               # NEVER call docker compose directly (C2)
log() { printf '\n==> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

wait_ready() {
    local i
    for i in $(seq 1 12); do
        curl -fsS "$READYZ_URL" >/dev/null 2>&1 && return 0
        sleep 5
    done
    return 1
}

on_failure() {
    local rc=$?
    # Best-effort recovery: drop errexit and the trap so a failing recovery command
    # cannot abort the handler before the diagnostics are printed (review S2).
    trap - ERR
    set +e
    printf '\nDEPLOY FAILED (exit=%s, stage=%s)\n' "$rc" "$STAGE" >&2
    case "$STAGE" in
        worktree)   # failed before touching the running service: restore worktree only (C5)
            git checkout --detach "$OLD_SHA"
            printf 'Worktree restored to %s; running service was never touched.\n' "$OLD_SHA" >&2
            printf 'NOTE: DB schema may have advanced. Backup: %s\n' "$LAST_BACKUP" >&2
            ;;
        service)    # new version failed readiness: full rollback on the previous image
            printf 'Rolling back service to previous image...\n' >&2
            git checkout --detach "$OLD_SHA"
            if docker image inspect "$IMAGE:prev" >/dev/null 2>&1; then
                docker tag "$IMAGE:prev" "$IMAGE:latest"
                compose up -d --no-build --force-recreate backend
                if wait_ready; then
                    printf 'Rolled back to %s and healthy again.\n' "$OLD_SHA" >&2
                else
                    printf 'OLD VERSION ALSO UNHEALTHY — manual intervention required.\n' >&2
                    printf 'Inspect: docker compose logs backend ; docker compose ps\n' >&2
                fi
            else
                printf 'No %s:prev image (first deploy?) — manual intervention required.\n' "$IMAGE" >&2
            fi
            printf 'NOTE: DB schema may have advanced (migrations are forward-only).\n' >&2
            printf 'Backup: %s — restore manually if needed.\n' "$LAST_BACKUP" >&2
            ;;
        *)  printf 'Nothing was changed.\n' >&2 ;;
    esac
    exit "$rc"
}

gen_env() {     # .env is a deploy-time artifact: compose interpolation + container env share it (S7)
    log "generating .env from Secret Manager"
    local secret_key pg_pw smtp_key
    secret_key=$(gcloud secrets versions access latest --secret=app-secret-key)
    pg_pw=$(gcloud secrets versions access latest --secret=app-postgres-password)
    smtp_key=$(gcloud secrets versions access latest --secret=app-smtp2go-api-key)
    # Unquoted dotenv values + a raw DSN embed: restrict to a charset safe for compose's .env
    # parser, the asyncpg URL, and shell (bootstrap creates secrets with `openssl rand -hex`).
    # NOT die: an explicit exit bypasses the ERR trap; `false` trips it so the worktree is restored.
    [[ "$pg_pw" =~ ^[A-Za-z0-9_-]+$ ]] \
        || { printf 'ERROR: app-postgres-password has .env/DSN-unsafe characters\n' >&2; false; }
    [[ "$secret_key" =~ ^[A-Za-z0-9_-]+$ ]] \
        || { printf 'ERROR: app-secret-key has .env-unsafe characters\n' >&2; false; }
    [[ "$smtp_key" =~ ^[A-Za-z0-9_-]+$ ]] \
        || { printf 'ERROR: app-smtp2go-api-key has .env-unsafe characters\n' >&2; false; }
    rm -f .env    # redirection onto an EXISTING file keeps its old mode; recreate so umask applies
    umask 177
    {
        printf '# GENERATED by deploy.sh %s — do not edit; regenerated every deploy\n' \
            "$(date -u +%FT%TZ)"
        printf 'POSTGRES_PASSWORD=%s\n' "$pg_pw"
        printf 'SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://postgres:%s@db:5432/postgres\n' "$pg_pw"
        printf 'REDIS_URL=redis://redis:6379\n'
        printf 'SECRET_KEY=%s\n' "$secret_key"
        printf 'SMTP2GO_API_KEY=%s\n' "$smtp_key"
        cat scripts/deploy-config.staging.env
    } > .env
    umask 022
}

main() {
    cd "$BACKEND_DIR"
    local target_ref="${1:-origin/main}" start_ts
    start_ts=$(date +%s)

    exec 9>"$LOCK_FILE"
    flock -n 9 || die "another deploy is already in progress"

    log "[1/9] preflight"
    docker info >/dev/null 2>&1 || die "docker daemon not running"
    command -v gcloud >/dev/null || die "gcloud not installed"
    command -v gsutil >/dev/null || die "gsutil not installed"
    command -v curl >/dev/null || die "curl not installed"
    [[ "$GCS_BUCKET" != *CHANGE_ME* ]] || die "GCS_BUCKET not configured (see bootstrap)"
    gcloud auth list --filter=status:ACTIVE --format='value(account)' | grep -q . \
        || die "no active gcloud identity (VM service account?)"
    [ -z "$(git status --porcelain)" ] || die "git working tree not clean"

    log "[2/9] recording rollback baseline (from the RUNNING container, not tags)"
    OLD_SHA=$(git rev-parse HEAD)
    local running_ctr running_img
    # Prefer the RUNNING container; fall back to stopped ones (crashed backend still has the right image).
    running_ctr=$(compose ps -q backend | head -n1 || true)
    [ -n "$running_ctr" ] || running_ctr=$(compose ps -aq backend | head -n1 || true)
    if [ -n "$running_ctr" ]; then
        running_img=$(docker inspect --format '{{.Image}}' "$running_ctr")
        docker tag "$running_img" "$IMAGE:prev"
        log "baseline: sha=$OLD_SHA image=$running_img"
    else
        log "WARNING: no existing backend container (first deploy?) — image rollback unavailable"
    fi

    log "[3/9] checking out ${target_ref}"
    git fetch --all --tags --prune
    trap on_failure ERR
    STAGE=worktree                      # from here, any failure restores the worktree
    git checkout --detach "$target_ref"
    log "deploying $(git rev-parse --short HEAD): $(git log -1 --format=%s)"

    log "[4/9] generating .env (after checkout, so new refs can add variables)"   # S2
    gen_env

    log "[5/9] building backend image"
    compose build backend

    log "[6/9] starting db + redis (waiting for healthy)"
    compose up -d --wait db redis

    log "[7/9] backing up DB to GCS before migrate"
    local ts
    ts=$(date +%Y%m%d-%H%M%S)
    LAST_BACKUP="$GCS_BUCKET/pre-deploy-$ts.sql.gz"
    compose exec -T db pg_dump -U postgres postgres | gzip | gsutil -q cp - "$LAST_BACKUP"
    log "backup done: $LAST_BACKUP"

    log "[8/9] migrate + seeds (in one-off backend containers — old container lacks new files)"  # C3
    compose run --rm backend alembic upgrade head
    # PYTHONPATH: the script imports `app.*`; WORKDIR is /app but `python scripts/x.py` puts only
    # scripts/ on sys.path (alembic is unaffected — its env.py resolves paths itself).
    compose run --rm -e PYTHONPATH=/app backend python scripts/seed_rbac.py
    if [ "${SEED_MOCK:-false}" = "true" ]; then
        log "applying mock-scenario seed (SEED_MOCK=true)"
        compose exec -T db psql -U postgres -d postgres -v ON_ERROR_STOP=1 \
            < scripts/seed_mock_scenarios.sql
    fi

    log "[9/9] starting new backend and waiting for readiness"
    STAGE=service                       # from here, failure = full image rollback
    compose up -d backend
    wait_ready || false                 # trigger the ERR trap explicitly on timeout

    trap - ERR
    docker image prune -f >/dev/null || true    # dangling only; :latest/:prev survive; never fail a good deploy
    log "DEPLOY OK — $(git rev-parse --short HEAD) in $(( $(date +%s) - start_ts ))s"
    log "rollback hint: ./scripts/deploy.sh $OLD_SHA"
}

main "$@"
