"""project settings and config fields

Feature 013 (Spec/013-project-settings-activity/decisions.md ADR-090~095):

- `project_settings`: the deployment's single global settings row (ADR-090). The single-row
  invariant is a unique index on the constant expression `(true)`, and the table joins
  AUDITED_TABLES so changing the disaster types is recorded.
- station/task property config gain `disaster_types` / `label` / `sort_order` / `is_active`
  (ADR-091/095), plus the UNIQUE key the application-level upsert has always assumed.
- `users.last_activity_at` (ADR-093), written on refresh-token rotation.

Hand-written, NOT autogenerated: the ARRAY server defaults, the expression-based unique
index and the column comments are exactly what autogenerate silently drops.

⚠️ The UNIQUE constraints can fail on pre-existing data, and the config tables are NOT
empty: migration a2a8e4d8c51d seeds 36 station and 10 task config rows (ADR-091's context
says otherwise — it only checked seed_rbac.py and seed_mock_scenarios.sql, and missed the
seeding done inside that migration). Those seeded rows are duplicate-free, so a database
built purely from migrations upgrades cleanly, but any deployment whose configs were also
written through the API must be checked first:

    SELECT station_type, property_name, count(*) FROM station_property_config
    GROUP BY 1,2 HAVING count(*) > 1;
    SELECT task_type, property_name, count(*) FROM task_property_config
    GROUP BY 1,2 HAVING count(*) > 1;

The seeded rows all get `disaster_types = '{}'`, so they stay enabled under every disaster
setting — no backfill needed.

Revision ID: 07ac630e0009
Revises: b7e4c1a90d52
Create Date: 2026-08-16

Chained after feature 012's *head* (PR #35) rather than after `e1f2a3b4c5d6`, which both
features branched from. Two revisions sharing one parent is two alembic heads the moment
both land on main, and `alembic upgrade head` refuses to run with more than one head.
Feature 012 merges first; until it does, this branch on its own cannot resolve its parent.

The parent is `b7e4c1a90d52`, not `f2b7c9d4e0a3`. It was `f2b7c9d4e0a3` when ADR-167 was
written, because that was feature 012's head at the time; PR #35 then added `b7e4c1a90d52`
(FK indexes for the search subqueries) on top of it. Chaining onto the old head would have
reproduced the exact two-head failure this revision exists to avoid — verified against a
real database (ADR-173).

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.db.triggers import get_audit_trigger_sql

# revision identifiers, used by Alembic.
revision: str = '07ac630e0009'
down_revision: str | Sequence[str] | None = 'b7e4c1a90d52'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CONFIG_TABLES = (
    ("station_property_config", "station_type"),
    ("task_property_config", "task_type"),
)


def upgrade() -> None:
    """Create project_settings, extend both config tables, and add users.last_activity_at."""
    op.create_table(
        "project_settings",
        sa.Column("uuid", sa.UUID(), nullable=False, comment="主鍵 UUID"),
        sa.Column("name", sa.String(100), nullable=False, comment="災害名稱，例如「花蓮 0816」"),
        sa.Column(
            "disaster_types", postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'"), nullable=False,
            comment="這場災害的型別集合，例如 {landslide,flood}",
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True, comment="災害起始時間"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False, comment="建立時間",
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False, comment="最後更新時間",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # 單列不變式：一個部署 = 一場（混合型）災害（ADR-090）
    op.execute(
        "CREATE UNIQUE INDEX uq_project_settings_singleton ON project_settings ((true))"
    )
    # project_settings joins AUDITED_TABLES — changing the disaster types is an audited act.
    op.execute(get_audit_trigger_sql("project_settings"))

    for table, type_col in _CONFIG_TABLES:
        op.add_column(table, sa.Column(
            "disaster_types", postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'"), nullable=False,
            comment="啟用於哪些災害型別；空陣列代表全部",
        ))
        op.add_column(table, sa.Column(
            "label", sa.String(100), nullable=True,
            comment="顯示文字；NULL 時前端回退顯示 property_name",
        ))
        op.add_column(table, sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False,
            comment="表單欄位順序",
        ))
        op.add_column(table, sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False,
            comment="停用開關",
        ))
        op.create_unique_constraint(f"uq_{table}_key", table, [type_col, "property_name"])

    op.add_column("users", sa.Column(
        "last_activity_at", sa.DateTime(timezone=True), nullable=True,
        comment="最後活動時間（refresh token 輪替時寫入）",
    ))


def downgrade() -> None:
    """Drop everything this revision added, in reverse order."""
    op.drop_column("users", "last_activity_at")

    for table, _type_col in _CONFIG_TABLES:
        op.drop_constraint(f"uq_{table}_key", table, type_="unique")
        for column in ("is_active", "sort_order", "label", "disaster_types"):
            op.drop_column(table, column)

    op.execute("DROP TRIGGER IF EXISTS audit_trigger_project_settings ON project_settings;")
    op.drop_index("uq_project_settings_singleton", table_name="project_settings")
    op.drop_table("project_settings")
