"""consolidate_password_fields

Revision ID: 4d87b614aece
Revises: 5c6103762349
Create Date: 2026-03-26 10:05:13.739016

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d87b614aece'
down_revision: str | Sequence[str] | None = '5c6103762349'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.drop_column('users', 'salt_backend', if_exists=True)
    op.drop_column('users', 'salt_frontend', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt_frontend', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('salt_backend', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
