"""add_salt_fields_to_user

Revision ID: 5c6103762349
Revises: 60fa7227481a
Create Date: 2026-03-25 16:32:53.915937

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c6103762349'
down_revision: str | Sequence[str] | None = '60fa7227481a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt_frontend', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('salt_backend', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt_backend')
    op.drop_column('users', 'salt_frontend')
    # ### end Alembic commands ###
