"""initial schema

Revision ID: 60fa7227481a
Revises: 
Create Date: 2026-02-08 20:41:28.058344

"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '60fa7227481a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('policies',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('read', sa.String(length=50), nullable=False),
    sa.Column('create', sa.String(length=50), nullable=False),
    sa.Column('edit', sa.String(length=50), nullable=False),
    sa.Column('delete', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最後更新時間'),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True, comment='軟刪除時間'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('base_geometries',
    sa.Column('property_name', sa.String(length=50), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('lane', sa.String(length=20), nullable=True),
    sa.Column('alley', sa.String(length=20), nullable=True),
    sa.Column('no', sa.String(length=20), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('room', sa.String(length=20), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最後更新時間'),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True, comment='軟刪除時間'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('policy_group_assign',
    sa.Column('group_uuid', sa.UUID(), nullable=False),
    sa.Column('policy_uuid', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.ForeignKeyConstraint(['group_uuid'], ['groups.uuid'], ),
    sa.ForeignKeyConstraint(['policy_uuid'], ['policies.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('policy_user_assign',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('policy_uuid', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.ForeignKeyConstraint(['policy_uuid'], ['policies.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_group_assign',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('group_uuid', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.ForeignKeyConstraint(['group_uuid'], ['groups.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('closure_areas',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('information_source', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uuid'], ['base_geometries.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('stations',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('op_hour', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uuid'], ['base_geometries.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('tickets',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['base_geometries.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('hr_requirements',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['tickets.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('request_photos',
    sa.Column('req_uuid', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最後更新時間'),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True, comment='軟刪除時間'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['req_uuid'], ['tickets.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('station_properties',
    sa.Column('station_uuid', sa.UUID(), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('weightings', sa.Float(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最後更新時間'),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True, comment='軟刪除時間'),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['station_uuid'], ['stations.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('supply_requirements',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['tickets.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('crowd_sourcing',
    sa.Column('station_uuid', sa.UUID(), nullable=False),
    sa.Column('item_uuid', sa.UUID(), nullable=True),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('user_credibility_score', sa.Float(), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('n_updates', sa.Integer(), nullable=False),
    sa.Column('distance_from_geometry', sa.Float(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最後更新時間'),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True, comment='軟刪除時間'),
    sa.ForeignKeyConstraint(['item_uuid'], ['station_properties.uuid'], ),
    sa.ForeignKeyConstraint(['station_uuid'], ['stations.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('hr_task_specialties',
    sa.Column('req_uuid', sa.UUID(), nullable=False),
    sa.Column('specialty_description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最後更新時間'),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True, comment='軟刪除時間'),
    sa.ForeignKeyConstraint(['req_uuid'], ['hr_requirements.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('supply_task_items',
    sa.Column('req_uuid', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('suggestion', sa.String(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='主鍵 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最後更新時間'),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True, comment='軟刪除時間'),
    sa.ForeignKeyConstraint(['req_uuid'], ['supply_requirements.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply_task_items')
    op.drop_table('hr_task_specialties')
    op.drop_table('crowd_sourcing')
    op.drop_table('supply_requirements')
    op.drop_table('station_properties')
    op.drop_table('request_photos')
    op.drop_table('hr_requirements')
    op.drop_table('tickets')
    op.drop_table('stations')
    op.drop_table('closure_areas')
    op.drop_table('user_group_assign')
    op.drop_table('policy_user_assign')
    op.drop_table('policy_group_assign')
    op.drop_table('base_geometries')
    op.drop_table('users')
    op.drop_table('policies')
    op.drop_table('groups')
    # ### end Alembic commands ###
