"""ticket disaster fields

Chained after **PR #48**'s head (`c3f0a1b2d4e6`, briefings) rather than after `main`'s head,
because this branch stacks on #48 and `main`'s `90c93167fa66` does not exist here. That means
**#49 and #48 must merge before this one**; until they do, `alembic upgrade head` on a branch
that lacks `c3f0a1b2d4e6` fails to resolve the parent. Same accepted cost, and the same
reasoning, as ADR-173.

Once #49/#48 reach main, `c3f0a1b2d4e6` and `90c93167fa66` are two heads sharing the parent
`07ac630e0009` — a pre-existing split this revision inherits rather than causes. It needs the
usual empty merge revision (precedent: `8ebfc3903041`, `c7d8e9f0a1b2`), which belongs to
whichever PR lands second, not here.

Feature 018 (Spec/018-ticket-disaster-fields/decisions.md ADR-244~251).

Six things, in dependency order:

1. `disaster_types` — the vocabulary table ADR-091 deliberately did not write, now that PM has
   delivered the six real types. A table rather than the `DisasterType` enum
   `app/core/disaster_types.py` reserved, because operators must be able to add a type through
   the API when an unplanned disaster arrives (ADR-244).
2. `data_type` rewritten across ALL THREE config tables, from storage-type names to
   widget names (ADR-245). See the `_DATA_TYPE_MAP` below; `downgrade()` inverts it.
3. `ticket_property_config` — the per-disaster field definitions, keyed on `property_name`
   alone (ADR-247), seeded with the fourteen fields. All three config tables then get a CHECK
   pinning `data_type` to the closed set, so the rewrite in (2) cannot be undone by a later
   hand-written INSERT — see `_constrain_data_type`.
4. `ticket_disaster_details` — the values.
5. `tickets.disaster_type` → `disaster_types text[]` (ADR-246), plus the two reporter triage
   columns; `secondary_locations` gains five space columns (ADR-249).
6. Audit triggers for every new table AND for the two pre-existing `*_property_config` tables,
   which were unaudited on every branch and which nobody had recorded as a gap (ADR-251).

Hand-written, NOT autogenerated: the ARRAY server defaults, the column comments, the data
backfills and the audit triggers are all things autogenerate silently drops.

⚠️ The `disaster_type` → `disaster_types` backfill also renames the value `mudslide`, which
`scripts/seed_mock_scenarios.sql` wrote to ~30 rows, to `landslide`. `mudslide` is not one of
the six keys, so without this those tickets would point at a vocabulary entry that does not
exist and silently render an empty disaster-field form. The seed script is fixed in the same
commit; this handles databases already carrying the old value.

Revision ID: e7b249d0af31
Revises: c3f0a1b2d4e6
Create Date: 2026-09-09

"""

import json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.triggers import get_audit_trigger_sql

# revision identifiers, used by Alembic.
revision: str = "e7b249d0af31"
down_revision: str | Sequence[str] | None = "c3f0a1b2d4e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Frozen snapshot: the tables THIS revision attaches triggers to. Deliberately not read from
# `app.db.triggers.AUDITED_TABLES` — that list grows over time, and a historical migration must
# not chase it, or a fresh `alembic upgrade head` would try to CREATE TRIGGER on tables that
# later revisions create. Same convention as 71bd05e07df3 and c219aac56556.
_FEATURE_018_AUDITED_TABLES = [
    "disaster_types",
    "station_property_config",
    "task_property_config",
    "ticket_property_config",
    "ticket_disaster_details",
]

_CONFIG_TABLES = ("station_property_config", "task_property_config")

# ADR-245. Old token -> new token. The inverse is not quite a bijection: `number` maps back to
# `Integer`, which is what all 46 existing rows were, so downgrade is lossless for them.
_DATA_TYPE_MAP = {
    "String": "text",
    "Text": "long_text",
    "Integer": "number",
    "Float": "number",
    "Boolean": "boolean",
    "Enum": "single_select",
    "Array": "multi_select",
}
_DATA_TYPE_MAP_INVERSE = {
    "text": "String",
    "long_text": "Text",
    "number": "Integer",
    "boolean": "Boolean",
    "single_select": "Enum",
    "multi_select": "Array",
}

# The closed set, mirroring app/graphql/shared.py::FieldDataType. Frozen here for the same
# reason as _FEATURE_018_AUDITED_TABLES: a historical migration must not chase a Python enum
# that later features extend, or a fresh `upgrade head` would write a constraint the rows of
# its own era cannot satisfy. Adding a widget later means a new revision that drops and
# re-adds these constraints, not an edit here.
_FIELD_DATA_TYPES = ("text", "long_text", "number", "boolean", "single_select", "multi_select")

_ALL_CONFIG_TABLES = (*_CONFIG_TABLES, "ticket_property_config")

# The six types PM delivered. 土石流 is `landslide` — the slug `project_settings.disaster_types`
# already gives as an example in its own column comment, and the one the constitution's Taiwan
# disaster list uses.
_DISASTER_TYPES = [
    ("flood", "水災"),
    ("landslide", "土石流"),
    ("epidemic", "疫情"),
    ("radiation", "核／輻射"),
    ("fire", "火災"),
    ("earthquake", "地震"),
]

# (property_name, data_type, unit, enum_options, disaster_types, label, hint)
#
# `access_blocked` and `entrance_blocked` each appear ONCE despite covering two disasters —
# that is the whole point of ADR-091's definition/activation split, and it is why their labels
# are the neutral wording rather than either disaster's phrasing: PM's table says
# 「出入口被水阻斷」 under 水災 and 「出入口被堵住」 under 土石流, and one row can only carry one.
_TICKET_FIELDS = [
    ("access_blocked", "single_select", None, ["yes", "no", "unknown"],
     ["flood", "landslide"], "出入口被阻斷", "明確 yes/no；不使用「有點困難」"),
    ("contact_precaution", "single_select", None,
     ["standard", "contactless_preferred", "contactless_required", "call_before_arrival",
      "remote_only"],
     ["epidemic"], "接觸方式", "記錄期待接觸類型，以協助志願者以低風險協助求救者"),
    ("crack_width_mm", "number", "mm", None, ["earthquake"], "最大可見裂縫實測值",
     "mm；>=0。有實測值時才填；不可為了量測靠近危險結構"),
    ("debris_depth_cm", "number", "cm", None, ["landslide"], "土砂堆積深度（若有實際測量）",
     "cm；>=0。可安全量測才填"),
    ("debris_entered_space", "single_select", None, ["yes", "no", "unknown"],
     ["landslide"], "土砂進入室內", "單一受災地點"),
    ("debris_movement_observed", "single_select", None, ["yes", "no", "unknown"],
     ["landslide"], "持續掉落或移動中的土砂", "可觀察事實，不是趨勢預測"),
    ("entrance_blocked", "single_select", None, ["yes", "no", "unknown"],
     ["fire", "earthquake"], "主要出入口被阻擋", "明確 yes/no；不代表專業安全判定"),
    ("professional_referral_requested", "single_select", None, ["yes", "no", "unknown"],
     ["epidemic"], "是否希望轉介專業單位", "只記求助者意願，不做檢傷診斷"),
    ("protective_action_status", "single_select", None,
     ["sheltering_indoors", "seeking_shelter", "evacuating_as_directed", "evacuated",
      "outdoors", "unknown"],
     ["radiation"], "目前所在狀態", "了解求救者的現下通報狀態"),
    ("unusual_odor_reported", "single_select", None,
     ["gas", "chemical", "other", "none", "unknown"],
     ["fire"], "瓦斯／不明氣味", "不得要求接近確認"),
    ("utility_hazards", "multi_select", None,
     ["gas_odor", "leaking_water", "exposed_wire", "sparks", "power_out", "other", "unknown"],
     ["earthquake"], "公共設施異常", "不要求自行檢查"),
    ("visible_flame", "single_select", None, ["yes", "no", "unknown"], ["fire"], "可見火焰",
     "眼前觀察"),
    ("visible_smoke", "single_select", None, ["yes", "no", "unknown"], ["fire"], "可見煙霧",
     "眼前觀察"),
    ("water_depth_cm", "number", "cm", None, ["flood"], "目前水深",
     "cm；>=0。有尺或可靠標示才填；不可為了量測進入危險區"),
]


def upgrade() -> None:
    """Create the vocabulary, the ticket field config and its values; reshape tickets."""
    _create_disaster_types()
    _rewrite_data_type_vocabulary()
    _create_ticket_property_config()
    _constrain_data_type()
    _create_ticket_disaster_details()
    _reshape_tickets()
    _extend_secondary_locations()

    for table in _FEATURE_018_AUDITED_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS audit_trigger_{table} ON {table};")
        op.execute(get_audit_trigger_sql(table))


def _create_disaster_types() -> None:
    op.create_table(
        "disaster_types",
        sa.Column("uuid", sa.UUID(), nullable=False, comment="主鍵 UUID"),
        sa.Column(
            "key", sa.String(50), nullable=False,
            comment="不可變更的英文小寫代碼，例如 flood；其他資料表以字串參照，無外鍵",
        ),
        sa.Column("label", sa.String(50), nullable=False, comment="顯示名稱，例如「水災」"),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False,
            comment="停用開關",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("key", name="uq_disaster_types_key"),
    )
    rows = ", ".join(f"(gen_random_uuid(), '{key}', '{label}')" for key, label in _DISASTER_TYPES)
    op.execute(f"INSERT INTO disaster_types (uuid, key, label) VALUES {rows}")


def _rewrite_data_type_vocabulary() -> None:
    """Rename the data_type tokens on the two pre-existing config tables, and add `unit`."""
    for table in _CONFIG_TABLES:
        op.add_column(table, sa.Column(
            "unit", sa.String(20), nullable=True,
            comment="number 欄位的單位，例如 cm、mm；其他型別為 NULL",
        ))
        for old, new in _DATA_TYPE_MAP.items():
            op.execute(
                f"UPDATE {table} SET data_type = '{new}' WHERE data_type = '{old}'"  # noqa: S608
            )


def _create_ticket_property_config() -> None:
    op.create_table(
        "ticket_property_config",
        sa.Column("uuid", sa.UUID(), nullable=False, comment="主鍵 UUID"),
        sa.Column("property_name", sa.String(100), nullable=False, comment="不可變更的欄位鍵"),
        sa.Column("data_type", sa.String(50), nullable=False, comment="前端渲染的控制項型別"),
        sa.Column("enum_options", sa.JSON(), nullable=True, comment="選項清單"),
        sa.Column(
            "unit", sa.String(20), nullable=True,
            comment="number 欄位的單位，例如 cm、mm；其他型別為 NULL",
        ),
        sa.Column(
            "disaster_types", postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'"), nullable=False,
            comment="啟用於哪些災害型別；空陣列代表全部",
        ),
        sa.Column(
            "label", sa.String(100), nullable=True,
            comment="顯示文字；NULL 時前端回退顯示 property_name",
        ),
        sa.Column(
            "hint", sa.String(200), nullable=True,
            comment="欄位下方的填寫提示與安全警語，例如「不可為了量測進入危險區」",
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False,
            comment="停用開關",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("property_name", name="uq_ticket_property_config_key"),
    )
    for name, data_type, unit, options, disasters, label, hint in _TICKET_FIELDS:
        op.execute(
            sa.text(
                "INSERT INTO ticket_property_config"
                " (uuid, property_name, data_type, enum_options, unit, disaster_types,"
                "  label, hint)"
                " VALUES (gen_random_uuid(), :name, :data_type, CAST(:options AS json), :unit,"
                "         CAST(:disasters AS varchar[]), :label, :hint)"
            ).bindparams(
                name=name,
                data_type=data_type,
                options=None if options is None else json.dumps(options),
                unit=unit,
                disasters="{" + ",".join(disasters) + "}",
                label=label,
                hint=hint,
            )
        )


def _constrain_data_type() -> None:
    """Pin `data_type` to the closed widget vocabulary on all three config tables.

    `_rewrite_data_type_vocabulary` above is a one-time data fix; without a constraint nothing
    stops a later hand-written INSERT from reintroducing an unmapped token. That is not a
    cosmetic problem: `FieldDataType(m.data_type)` in the GraphQL `from_model` raises
    `ValueError`, which the MaskErrors allow-list passes straight through, so ONE bad row makes
    the WHOLE `stationPropertyConfigs` query return `data: null`. A CHECK turns that into a
    rejected write, and turns any pre-existing stray row into a migration failure that names
    its table — loud at deploy time instead of silent until someone opens a form.

    Guarded DO block rather than `ADD CONSTRAINT ... IF NOT EXISTS`, which Postgres does not
    support for table constraints; the guard is what makes a re-run idempotent.
    """
    allowed = ", ".join(f"'{token}'" for token in _FIELD_DATA_TYPES)
    for table in _ALL_CONFIG_TABLES:
        op.execute(
            f"""
            DO $$ BEGIN
              IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'ck_{table}_data_type'
              ) THEN
                ALTER TABLE {table} ADD CONSTRAINT ck_{table}_data_type
                  CHECK (data_type IN ({allowed}));
              END IF;
            END $$;
            """
        )


def _create_ticket_disaster_details() -> None:
    op.create_table(
        "ticket_disaster_details",
        # A surrogate uuid PK, not the natural (ticket_uuid, property_name, value) composite:
        # audit_trigger_func() does `r_id := NEW.uuid` unconditionally, so a table without a
        # uuid column raises on every write.
        sa.Column("uuid", sa.UUID(), nullable=False, comment="主鍵 UUID"),
        sa.Column("ticket_uuid", sa.UUID(), nullable=False, comment="所屬通報單"),
        sa.Column(
            "property_name", sa.String(100), nullable=False,
            comment="對應 ticket_property_config.property_name，以字串參照，無外鍵",
        ),
        sa.Column(
            "value", sa.String(), nullable=False,
            comment="單一值；multi_select 欄位每個選項各一列",
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False, comment="建立時間",
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False, comment="最後更新時間",
        ),
        sa.Column("delete_at", sa.DateTime(timezone=True), nullable=True, comment="軟刪除時間"),
        sa.ForeignKeyConstraint(["ticket_uuid"], ["tickets.uuid"]),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint(
            "ticket_uuid", "property_name", "value", name="uq_ticket_disaster_detail_value"
        ),
    )
    op.create_index(
        "ix_ticket_disaster_details_ticket_uuid", "ticket_disaster_details", ["ticket_uuid"]
    )


def _reshape_tickets() -> None:
    op.add_column("tickets", sa.Column(
        "disaster_types", postgresql.ARRAY(sa.String()),
        server_default=sa.text("'{}'"), nullable=False,
        comment="災害型別集合，參照 disaster_types.key；已排序去重",
    ))
    # Backfill, folding the stale seed value into the real key on the way. `mudslide` was
    # never one of the six; see the module docstring.
    op.execute(
        "UPDATE tickets SET disaster_types = ARRAY[CASE disaster_type"
        " WHEN 'mudslide' THEN 'landslide' ELSE lower(trim(disaster_type)) END]"
        " WHERE disaster_type IS NOT NULL AND trim(disaster_type) <> ''"
    )
    op.drop_column("tickets", "disaster_type")

    op.add_column("tickets", sa.Column(
        "person_trapped_reported", sa.String(20), nullable=True,
        comment="災民受困／無法自行離開：yes/no/unknown",
    ))
    op.add_column("tickets", sa.Column(
        "immediate_danger_reported", sa.String(20), nullable=True,
        comment="立即生命危險：yes/no/unknown",
    ))


def _extend_secondary_locations() -> None:
    for column in (
        sa.Column("building_section", sa.String(50), nullable=True,
                  comment="樓棟／區域，例如 A棟、東翼；不知道可留空"),
        sa.Column("space_description", sa.String(100), nullable=True,
                  comment="空間描述，例如「三房兩廳」"),
        sa.Column("victim_space", sa.String(100), nullable=True,
                  comment="求救者所在空間，例如「主臥衣櫃」"),
        sa.Column("access_status", sa.String(20), nullable=True,
                  comment="可否進入（當下觀察，非安全鑑定）"),
        sa.Column("landmark_note", sa.String(), nullable=True,
                  comment="地標補充；座標不足時用來找到入口"),
    ):
        op.add_column("secondary_locations", column)


def downgrade() -> None:
    """Reverse everything, in the mirror order."""
    for table in reversed(_FEATURE_018_AUDITED_TABLES):
        op.execute(f"DROP TRIGGER IF EXISTS audit_trigger_{table} ON {table};")

    # Must come before the _DATA_TYPE_MAP_INVERSE rewrite below: restoring 'Enum' / 'Array'
    # violates a CHECK that only allows the new tokens, so dropping it first is not tidiness.
    for table in _ALL_CONFIG_TABLES:
        op.execute(f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS ck_{table}_data_type;")

    for column in (
        "landmark_note", "access_status", "victim_space", "space_description",
        "building_section",
    ):
        op.drop_column("secondary_locations", column)

    op.drop_column("tickets", "immediate_danger_reported")
    op.drop_column("tickets", "person_trapped_reported")
    op.add_column("tickets", sa.Column("disaster_type", sa.String(50), nullable=True))
    # Lossy by nature: a two-disaster ticket cannot fit in a scalar, so it keeps its first
    # type. Recorded rather than hidden — the array is the reason this column went away.
    op.execute(
        "UPDATE tickets SET disaster_type = disaster_types[1]"
        " WHERE cardinality(disaster_types) > 0"
    )
    op.drop_column("tickets", "disaster_types")

    op.drop_index("ix_ticket_disaster_details_ticket_uuid", table_name="ticket_disaster_details")
    op.drop_table("ticket_disaster_details")
    op.drop_table("ticket_property_config")

    for table in _CONFIG_TABLES:
        for new, old in _DATA_TYPE_MAP_INVERSE.items():
            op.execute(
                f"UPDATE {table} SET data_type = '{old}' WHERE data_type = '{new}'"  # noqa: S608
            )
        op.drop_column(table, "unit")

    op.drop_table("disaster_types")
