"""add_unique_constraint_to_user_group_assign

Revision ID: ecff746c61a6
Revises: 4d87b614aece
Create Date: 2026-03-27 21:05:58.930499

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ecff746c61a6'
down_revision: str | Sequence[str] | None = '4d87b614aece'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_group', 'user_group_assign', ['user_uuid', 'group_uuid'], if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_group', 'user_group_assign', type_='unique')
    # ### end Alembic commands ###
