"""search_text generated columns + trigram GIN indexes (feature 011)

Adds a PostgreSQL-generated `search_text` column to every searchable table, indexed with
pg_trgm's gin_trgm_ops. Chinese keyword search uses trigram matching rather than tsvector
because PostgreSQL's full-text search does not segment Chinese — "花蓮縣光復鄉" becomes a
single token and searching "光復" finds nothing (ADR-078).

The column list per table is the implementation of ADR-079's positive list: PII
(contact_*) and free-text note fields (comment / progress_note / pole_note) never enter
the index. Long text columns are truncated at 500 characters so the index cost stays
bounded regardless of what users paste in (ADR-081).

Hand-written, not autogenerated: computed columns, the gin_trgm_ops operator class and
column comments are all outside what Alembic's autogenerate reliably detects.

Revision ID: f2b7c9d4e0a3
Revises: e1f2a3b4c5d6
Create Date: 2026-08-16

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f2b7c9d4e0a3'
down_revision: str | Sequence[str] | None = 'e1f2a3b4c5d6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Keep in sync with the Computed(...) declarations in app/models/*.py and with
# EXPECTED_SOURCE_COLUMNS in tests/test_search_schema.py. That test fails if the two
# drift apart, which is the point.
_TRUNCATE = 500


def _plain(column: str) -> str:
    return f"coalesce({column}, '')"


def _truncated(column: str) -> str:
    return f"left(coalesce({column}, ''), {_TRUNCATE})"


def _expr(*fragments: str) -> str:
    return " || ' ' || ".join(fragments)


_SEARCH_TEXT: list[tuple[str, str]] = [
    ("stations", _expr(_plain("name"), _truncated("description"))),
    ("tickets", _expr(_plain("title"), _truncated("description"))),
    ("ticket_tasks", _expr(_plain("task_name"), _truncated("task_description"))),
    ("station_properties", _plain("property_name")),
    ("task_properties", _expr(_plain("property_name"), _truncated("property_value"))),
    (
        "secondary_locations",
        _expr(
            _plain("county"),
            _plain("city"),
            _plain("lane"),
            _plain("alley"),
            _plain("no"),
            _plain("floor"),
            _plain("room"),
            _plain("pole_id"),
        ),
    ),
]


def upgrade() -> None:
    """Add pg_trgm, the generated columns and their GIN indexes."""
    # Must precede any gin_trgm_ops index.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    for table, expr in _SEARCH_TEXT:
        # `varchar` + NOT NULL, not `text` and nullable: this must match exactly what
        # Base.metadata.create_all emits for `Mapped[str] = mapped_column(String,
        # Computed(..., persisted=True))`, because the test database is built by
        # create_all and production by this migration. NOT NULL is safe — every part of
        # the expression is coalesce()-wrapped, so the result is never NULL. (ADR-149)
        op.execute(
            f"ALTER TABLE {table} ADD COLUMN search_text varchar "
            f"GENERATED ALWAYS AS ({expr}) STORED NOT NULL"
        )
        op.execute(
            f"CREATE INDEX ix_{table}_search_text_trgm "
            f"ON {table} USING gin (search_text gin_trgm_ops)"
        )

    # These two columns are named after 巷/弄 but hold something else in practice. The
    # comments are the cheap half of the fix; renaming them would touch the GraphQL types
    # and the frontend forms, so that is deliberately left to a separate change.
    op.execute(
        "COMMENT ON COLUMN secondary_locations.lane IS "
        "'路／街名（road）——欄位名為 lane，但實際存路名，非巷'"
    )
    op.execute(
        "COMMENT ON COLUMN secondary_locations.alley IS "
        "'巷弄——欄位名為 alley，但實際存巷弄'"
    )


def downgrade() -> None:
    """Drop the generated columns and indexes; deliberately keep the extension."""
    op.execute("COMMENT ON COLUMN secondary_locations.alley IS NULL")
    op.execute("COMMENT ON COLUMN secondary_locations.lane IS NULL")

    for table, _ in reversed(_SEARCH_TEXT):
        # DROP COLUMN removes the index with it; the explicit DROP INDEX keeps the intent
        # readable in the diff and makes a partially-applied upgrade recoverable.
        op.execute(f"DROP INDEX IF EXISTS ix_{table}_search_text_trgm")
        op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS search_text")

    # pg_trgm is intentionally NOT dropped: an extension is a database-wide capability and
    # other objects or migrations may already depend on it. downgrade therefore does not
    # return the database to its exact prior state, by design.
